### ISSUE TITLE
ModuleNotFoundError: No module named 'scikit_learn'

### ISSUE THREAD

**Issue by LMarino1** [mistkml/mistk#11]
Hello, I'm trying to get the toolkit running but keep running into the above error.

Here's what the terminal logs when attempting to run the `python -m mistk scikit_learn.logistic_regression ScikitLearnLogisticRegressionModel 8080` command in your documentation:

```Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mistk/__main__.py", line 28, in <module>
    _module = importlib.import_module(sys.argv[1])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scikit_learn'
```

I'm running Ubuntu 20.04.1 with Python 3.8.10 
Thank you!

**Comment by yrrah** [comment]
there is a separate install step in addition to installing mistk, double check that you installed this module
https://github.com/mistkml/mistk/tree/master/examples/models/logistic-regression
