### ISSUE TITLE
Error when installing test harness wheel

### ISSUE THREAD

**Issue by cjdoucette** [mistkml/mistk#2]
It seems that `https://pypi.org/simple/mistk/` no longer exists.

```
$ pip3 install mistk_test_harness-0.4.5-py3-none-any.whl
Processing ./mistk_test_harness-0.4.5-py3-none-any.whl
Collecting docker==2.7.0 (from mistk-test-harness==0.4.5)
  Downloading https://files.pythonhosted.org/packages/6b/01/74d61c7de9fb99cebbbfab62ee5c88a9b23e8b1c25a57eded5fc22e87bd2/docker-2.7.0-py2.py3-none-any.whl (119kB)
    100% |████████████████████████████████| 122kB 2.1MB/s
Collecting scipy==1.0.0 (from mistk-test-harness==0.4.5)
  Using cached https://files.pythonhosted.org/packages/d8/5e/caa01ba7be11600b6a9d39265440d7b3be3d69206da887c42bef049521f2/scipy-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy==1.13.3 (from mistk-test-harness==0.4.5)
  Downloading https://files.pythonhosted.org/packages/57/a7/e3e6bd9d595125e1abbe162e323fd2d06f6f6683185294b79cd2cdb190d5/numpy-1.13.3-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 89kB/s
Collecting mistk (from mistk-test-harness==0.4.5)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/mistk/
```

**Comment by shelbydavis** [comment]
You have to install the mistk and mistk_test_harness at the same time if you're using python wheel files. They're not in the pypi repository (yet).
e.g.
`pip3 install https://github.com/mistkml/mistk/releases/download/0.4.5/mistk-0.4.5-py3-none-any.whl https://github.com/mistkml/mistk/releases/download/0.4.5/mistk_test_harness-0.4.5-py3-none-any.whl`

**Comment by cjdoucette** [comment]
That worked. Thank you!
